SELECT 
    UNITUPI, UNITAP, UNITUP, 
    KD_PROV, PROVINSI, 
    KD_KAB, KABUPATENKOTA, 
    KD_KEC, KECAMATAN, 
    KD_KEL, DESAKELURAHAN,
    COUNT(*) AS JML,
    max(LATITUDE) AS LAT_INDUK,
    max(LONGITUDE)  AS LON_INDUK,
    KATEGORI, 
    SUM(CASE WHEN VOLUME IS NOT NULL THEN VOLUME ELSE 1 END) AS VOLUME,
    KDSATUAN,
    SUM(RUPIAH_SATUAN) AS RUPIAH_SATUAN,
    'DETAIL' AS TIPE
FROM LISDESBPBL.TRANS_JARINGAN_LISTRIK
GROUP BY 
    UNITUPI, UNITAP, UNITUP, 
    KD_PROV, PROVINSI, 
    KD_KAB, KABUPATENKOTA, 
    KD_KEC, KECAMATAN, 
    KD_KEL, DESAKELURAHAN,
    KATEGORI,
    KDSATUAN
order by UNITUPI, UNITAP, UNITUP, 
    KD_PROV,  
    KD_KAB, 
    KD_KEC, 
    KD_KEL;
