-- MASTER per KECAMATAN + DETAIL
SELECT *
FROM (
    -- MASTER per KECAMATAN
    SELECT m.UNITUPI, m.UNITAP, m.UNITUP,
           m.KD_PROV, m.PROVINSI,
           m.KD_KAB, m.KABUPATENKOTA,
           m.KD_KEC, m.KECAMATAN,
           CAST(NULL AS VARCHAR2(10)) AS KD_KEL,
           CAST(NULL AS VARCHAR2(100)) AS DESAKELURAHAN,
           m.JML,
           m.LAT_INDUK,
           m.LON_INDUK,
           CAST(NULL AS VARCHAR2(50)) AS KATEGORI,
           CAST(NULL AS NUMBER) AS VOLUME,
           CAST(NULL AS VARCHAR2(20)) AS KDSATUAN,
           m.RUPIAH_TOTAL,
           'MASTER_KEC' AS TIPE,
           1 AS SORT_ORDER
    FROM (
        SELECT UNITUPI, UNITAP, UNITUP,
               KD_PROV, PROVINSI,
               KD_KAB, KABUPATENKOTA,
               KD_KEC, KECAMATAN,
               COUNT(*) AS JML,
               AVG(LATITUDE) AS LAT_INDUK,
               AVG(LONGITUDE) AS LON_INDUK,
               SUM(RUPIAH_SATUAN) AS RUPIAH_TOTAL
        FROM LISDESBPBL.TRANS_JARINGAN_LISTRIK
        GROUP BY UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA, KD_KEC
    ) m
    UNION ALL
    -- DETAIL per record
    SELECT 
        UNITUPI, UNITAP, UNITUP,
        KD_PROV, PROVINSI,
        KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN,
        KD_KEL, DESAKELURAHAN,
        1 AS JML,
        LATITUDE AS LAT_INDUK,
        LONGITUDE AS LON_INDUK,
        KATEGORI,
        VOLUME,
        KDSATUAN,
        RUPIAH_SATUAN,
        'DETAIL' AS TIPE,
        2 AS SORT_ORDER
    FROM LISDESBPBL.TRANS_JARINGAN_LISTRIK
) t
ORDER BY 
    UNITUPI, UNITAP, UNITUP,
    KD_PROV, KD_KAB, KD_KEC, KD_KEL,
    SORT_ORDER,
    KATEGORI;
