SELECT 
    UNITUPI, UNITAP, UNITUP, 
    KD_PROV, PROVINSI, 
    KD_KAB, KABUPATENKOTA, 
    KD_KEC, KECAMATAN, 
    KD_KEL, DESAKELURAHAN,
    COUNT(*) AS JML,
    MAX(CASE WHEN PARENT_ID IS NULL THEN LATITUDE END) AS LAT_INDUK,
    MAX(CASE WHEN PARENT_ID IS NULL THEN LONGITUDE END) AS LON_INDUK,
    null KATEGORI, 
    null VOLUME,
    null KDSATUAN,
    SUM(RUPIAH_SATUAN) AS RUPIAH_SATUAN,
    'MASTER' AS TIPE
FROM LISDESBPBL.TRANS_JARINGAN_LISTRIK
GROUP BY 
    UNITUPI, UNITAP, UNITUP, 
    KD_PROV, PROVINSI, 
    KD_KAB, KABUPATENKOTA, 
    KD_KEC, KECAMATAN, 
    KD_KEL, DESAKELURAHAN
