CREATE TABLE LISDESBPBL.MASTER_MATERIAL (
  ID_MATERIAL  NUMBER GENERATED AS IDENTITY PRIMARY KEY,
  KD_MATERIAL  VARCHAR2(10 BYTE) UNIQUE,
  KATEGORI     VARCHAR2(100 BYTE),
  CONSTRAINT UQ_MASTER_MATERIAL_KATEGORI UNIQUE (KATEGORI)
);
