-- ============================================================
-- 2?? Pastikan struktur tabel sesuai (versi fix)
-- ============================================================
-- Gunakan ini jika tabel belum ada. Jika sudah, skip bagian ini.
CREATE TABLE LISDESBPBL.MASTER_HARGA_MDU
(
  ID_HARGA       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UNITUPI        VARCHAR2(5 BYTE)   NOT NULL,
  UNITAP         VARCHAR2(5 BYTE)   NOT NULL,
  UNITUP         VARCHAR2(5 BYTE)   NOT NULL,
  ID_MDU         VARCHAR2(10 BYTE)  NOT NULL,
  KD_MATERIAL    VARCHAR2(3 BYTE),
  KATEGORI       VARCHAR2(200 BYTE),
  NAMA_SKU       VARCHAR2(400 BYTE),
  SPESIFIKASI    VARCHAR2(400 BYTE),
  VOLUME         NUMBER,
  KDSATUAN       VARCHAR2(10 BYTE),
  SATUAN         VARCHAR2(50 BYTE),
  RUPIAH_SATUAN  NUMBER(12,2)       DEFAULT 0 NOT NULL,
  TGL_UPDATE     DATE               DEFAULT SYSDATE,
  USER_UPDATE    VARCHAR2(50 BYTE),
  CONSTRAINT UQ_HARGA_ULP_MDU UNIQUE (UNITUPI, UNITAP, UNITUP, ID_MDU)
);
/