CREATE TABLE UNITUPI
(
  UNITUPI     VARCHAR2(2 BYTE),
  SATUAN      VARCHAR2(25 BYTE),
  NAMA        VARCHAR2(50 BYTE),
  ALAMAT      VARCHAR2(50 BYTE),
  TELEPON     VARCHAR2(25 BYTE),
  FAXIMILE    VARCHAR2(25 BYTE),
  MANAGER     VARCHAR2(50 BYTE),
  KOTA        VARCHAR2(50 BYTE),
  UNITUPIERP  VARCHAR2(4 BYTE),
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS
)