SET DEFINE OFF;
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA)
 Values
   ('54', 'UID', 'JAKARTA RAYA', 'JAKARTA', 'SYAMSUL HUDA', 
    'JAKARTA');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA, UNITUPIERP)
 Values
   ('55', 'UID', 'BALI', 'JL. LETDA TANTULAR', '0361 221960', 
    '0361 999999', 'I WAYAN UDAYANA', 'BALI', '55');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA, UNITUPIERP)
 Values
   ('51', 'UID', 'JAWA TIMUR', 'Jl. Embong Trengguli 19-21 Surabaya', '(031) - 5340651-55', 
    '5310057', 'LASIRAN', 'SURABAYA', '5100');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('53', 'UID', 'JAWA BARAT', 'JL. ASIA AFRIKA NO 1', '022-123456', 
    '022-123456', 'AGUNG NUGRAHA', 'BANDUNG');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA, UNITUPIERP)
 Values
   ('52', 'UID', 'JAWA TENGAH DAN DIY', 'JL. TEUKU UMAR 47 SEMARANG', '123', 
    '123', 'M. IRWANSYAH PUTRA', 'SEMARANG', '5200');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA, UNITUPIERP)
 Values
   ('16', 'UIW', 'BANGKA BELITUNG', 'JL. SOEKARNO HATTA KM 5', '0717-439300', 
    '0717-439600', 'JOKO NUR ASTANTO', 'PANGKALPINANG', '16');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA)
 Values
   ('22', 'UIW', 'KALIMANTAN SELATAN DAN TENGAH', 'JL. PANGLIMA BATUR BARAT', 'PRIYO WURIANTO', 
    'BANJARBARU');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('41', 'UIW', 'MALUKU DAN MALUKU UTARA', 'JL. DIPONEGORO NO. 02 AMBON', '0', 
    '0', 'ROMANTIKA DWI JUNI PUTRA', 'AMBON');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA)
 Values
   ('11', 'UIW', 'ACEH', 'JL. TGK. MOHD DAUD BEUREUEH 172', 'BOB SARIL', 
    'BANDA ACEH');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA, UNITUPIERP)
 Values
   ('12', 'UIW', 'SUMATERA UTARA', 'SUMATERA UTARA', 'PANDAPOTAN MANURUNG', 
    'MEDAN', '1200');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('13', 'UIW', 'SUMATERA BARAT', 'JL. DR. WAHIDIN NO. 8', '0751-33446', 
    '123', 'BAMBANG YUSUF', 'PADANG');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('18', 'UIW', 'RIAU DAN KEPRI', 'JL. SETYABUDI PEKANBARU', '123', 
    '123', 'AGUNG MURDIFI', 'PEKANBARU');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA)
 Values
   ('42', 'UIW', 'PAPUA DAN PAPUA BARAT', 'JL. A.YANI NO 18', 'ABDUL FARID', 
    'JAYAPURA');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA, UNITUPIERP)
 Values
   ('31', 'UIW', 'SULUTTENGGO', 'JL BATHESDA NO. 32', '(0431) 863644', 
    '(0431) 863660', 'BARINGIN NABABAN', 'MANADO', '3100');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('21', 'UIW', 'KALIMANTAN BARAT', 'JL. ADI SUCIPTO KM. 7,3 SEI RAYA', '0561722037', 
    '0561721395', 'JOHANES AVILLA ARI DARTOMO', 'PONTIANAK');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('44', 'UIW', 'NUSA TENGGARA BARAT', 'JL LANGKO NO 25-27', '(0370) 643123', 
    '(0370) 634401', 'SUDJARWO', 'MATARAM');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('32', 'UIW', 'SULSELRABAR', 'JL HERTASNING BLOK B PANAKKUKANG', '(0411) 444488', 
    '(0411) 444800', 'AWALUDDIN HAFID', 'MAKASSAR');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA, UNITUPIERP)
 Values
   ('17', 'UID', 'LAMPUNG', 'LAMPUNG', 'PANDAPOTAN MANURUNG', 
    'LAMPUNG', '1700');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('14', 'UIW', 'S2JB', 'JL. KAPTEN A RIVAI NO. 37 ', '0711-358355', 
    '0711-310376', 'DARYONO', 'PALEMBANG');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, MANAGER, 
    KOTA)
 Values
   ('23', 'UIW', 'KALIMANTAN TIMUR', 'JL. MT HARYONO 384', 'JOICE LANNY WANTANIA', 
    'BALIKPAPAN');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('43', 'UIW', 'NUSA TENGGARA TIMUR', 'JL. PIET A. TALLO', '(0380) 8554005', 
    '(0380) 8554010', 'IGNATIUS RENDROYOKO', 'KUPANG');
Insert into UNITUPI
   (UNITUPI, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, MANAGER, KOTA)
 Values
   ('56', 'UID', 'BANTEN', 'Jln. Jenderal Sudirman No.1, Tangerang 15118', '123', 
    '123', 'SANDIKA AFLIANTO', 'BANTEN');
COMMIT;
