CREATE TABLE UNITAP
(
  UNITAP      VARCHAR2(10 BYTE),
  SATUAN      VARCHAR2(25 BYTE),
  NAMA        VARCHAR2(25 BYTE),
  ALAMAT      VARCHAR2(50 BYTE),
  TELEPON     VARCHAR2(25 BYTE),
  FAXIMILE    VARCHAR2(25 BYTE),
  UNITUPI     VARCHAR2(2 BYTE),
  MANAGER     VARCHAR2(50 BYTE),
  KOTA        VARCHAR2(50 BYTE),
  UNITAPLAMA  VARCHAR2(2 BYTE),
  UNITAPERP   VARCHAR2(4 BYTE),
  NMSINGKAT   VARCHAR2(10 BYTE),
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS
)