SET DEFINE OFF;
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54110', 'UP3', 'Menteng', 'Jl. M.I.R. Rais No.1', '3454000', 
    '3846508', '54', 'HENDRATUA PARULIAN MANURUNG', 'JAKARTA ', '54', 
    'MTG ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54130', 'UP3', 'Cempaka Putih', 'Jl. Jend A.Yani No. 60', '4255050', 
    '4258152', '54', 'SUPRIYADI', 'JAKARTA ', '54', 
    'CPP ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54210', 'UP3', 'Bandengan', 'Jl. Bandengan Utara No.79', '6600149', 
    '6693500', '54', 'MEYRINA P. TURAMBI', 'JAKARTA ', '54', 
    'BDG ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54310', 'UP3', 'Bulungan ', 'Jl. Sisingamangaraja No.1, Kebayoran Baru ', '7208333', 
    '7247828', '54', 'DASIH LISTYANTO', 'JAKARTA ', '54', 
    'BLG ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54330', 'UP3', 'KEBON JERUK', 'Jl HOS Cokroaminoto No.1 Kreo,Larangan,Tangerang', '5852534', 
    '5871458', '54', 'ELPIS J SINAMBELA', 'JAKARTA ', '54', 
    'KBJ ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54360', 'UP3', 'Ciputat', 'Jl. RE. Martadinata Km.27, Ciputat', '7440802', 
    '7443804', '54', 'SYAIFUL AZHARI SIREGAR', 'TANGERANG ', '54', 
    'CPT ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54380', 'UP3', 'Bintaro', 'Jl. Bintaro Utama Sektor 3 Rukan Bintaro Blok C No', '7375847', 
    '7375843', '54', 'HENDAR PRISNADIANTA Y', 'JAKARTA ', '54', 
    'BTR ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54410', 'UP3', 'Jatinegara', 'Jl. Jatinegara Timur No.75', '8504426', 
    '8192192', '54', 'MULKE GAL TUMANKEN', 'JAKARTA ', '54', 
    'KPM ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54420', 'UP3', 'Pondok Kopi', 'Jl. Sentra Primer baru Timur, Pulogebang', '4806504', 
    '4807160', '54', 'ARI TIRTAPRAWITA', 'JAKARTA ', '54', 
    'PKP ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54510', 'UP3', 'Tanjung Priok ', 'Jl. Yos Sudarso No.85, Sunter 1 ', '6510113', 
    '6510077', '54', 'HASUDUNGAN SIAHAAN', 'JAKARTA ', '54', 
    'STR ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54530', 'UP3', 'Marunda', 'Ruko Koja Baru Blok A No.10 - 11, Jl. Bhayangkara ', '9173393', 
    '43905220 ', '54', 'IRVAN HARDIANSYAH', 'JAKARTA UTARA ', '54', 
    'MRD ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, KOTA, UNITAPERP, NMSINGKAT)
 Values
   ('54610', 'UP3', 'Cikokol', 'Jl. Jend Sudirman No. 1 ', '5526716', 
    '5526721', '54', 'TANGERANG ', '54', 'CKK ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54620', 'UP3', 'SERPONG', 'Jl. Raya Serpong BSD Sektor 8 ', '5372708', 
    '5372712', '54', 'BUSRAN LABINTANG', 'TANGERANG ', '54', 
    'SRP ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54630', 'UP3', 'CENGKARENG', 'Jl. Lingkar Duri Kosambi, Cengkareng', '5440330', 
    '5440340', '54', 'ROBIN SEPTAVYN', 'JAKARTA ', '54', 
    'CKR ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54640', 'UP3', 'Cikupa', 'Jl. Raya Serang Km 17, Cikupa ', '5960724', 
    '5960725', '54', 'FRANSIS AL ZAUHARI', 'TANGERANG ', '54', 
    'CKP ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54660', 'UP3', 'Teluk Naga', 'Jl. Raya Kampung Melayu No.11 ', '55932719 ', 
    '55932719 ', '54', 'HELMI ACHMAD BANTAM', 'TANGERANG ', '54', 
    'TNG ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54710', 'UP3', 'KRAMAT JATI', 'Jl. Raya Bogor Km.20', '8093636', 
    '8094383', '54', 'BENY INDRA PRAJA', 'JAKARTA ', '54', 
    'CDT ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54720', 'UP3', 'CIRACAS', 'Jl. Raya Centex No.1 Ciracas', '8726605', 
    '8726604', '54', 'ANTON SUPRAPTO ADI', 'JAKARTA ', '54', 
    'CRS ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54730', 'UP3', 'Pondok Gede', 'Jl. Raya Jatimakmur No.150', '8488385', 
    '8488387', '54', 'YUSRA HELMI', 'JAKARTA ', '54', 
    'PGD ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54740', 'UP3', 'Lenteng Agung', 'Jl. Raya Duren Tiga No.100 Pancoran', '79184936', 
    '7817984', '54', 'MARTHA ADI NUGRAHA', 'JAKARTA ', '54', 
    'LAN ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54820', 'UP3', 'Prima Tangerang', 'Pekan Raya Jakarta', '817822223', 
    '3865205', '54', 'Drs. JATI G.P. SIAHAAN AK.', 'JAKARTA SELATAN ', '54', 
    'PTG ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54830', 'UP3', 'Prima Utara', 'Pekan Raya Jakarta', '817822223', 
    '3865205', '54', 'SUGENG WIDODO', 'JAKARTA SELATAN ', '54', 
    'PTU ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('54840', 'UP3', 'Prima Selatan', 'Jl. Warung Buncit No. 10 Jakarta 12740', '79192259,79192212', 
    '79197328', '54', 'Drs. JUSUP HUDIHARTO', 'JAKARTA SELATAN ', '54', 
    'PTS ');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51SBU', 'UP3', 'SURABAYA UTARA', 'JL. GEMBLONGAN 64 SURABAYA 60174', '(031) - 5340151-4', 
    '5353959', '51', 'ZAMZAMI', 'SURABAYA', '01', 
    '5111', 'SBU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51SBS', 'UP3', 'SURABAYA SELATAN', 'JL. NGAGEL TIMUR 14 - 16 SURABAYA 60283', '(031) - 5042572-73', 
    'ï¿½5042405', '51', 'MOCHAMAD ABDUL BASYID NURUL F.', 'SURABAYA', '02', 
    '5112', 'SBS');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51SBB', 'UP3', 'SURABAYA BARAT', 'JL RAYA TAMAN NO. 48D SEPANJANG SURABAYA', '(031) - 7668488, 7668444', 
    ' 7668844', '51', 'CYNTHIA DEWI ARIYANI', 'SURABAYA', '03', 
    '5113', 'SBB');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51MJK', 'UP3', 'MOJOKERTO', 'JL. RA. BASUNI 67 SOOKO MOJOKERTO 61361', '(0321) - 322705', 
    'ï¿½322704', '51', 'M.SYAFDINNUR', 'MOJOKERTO', '04', 
    '5114', 'MJK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51GSK', 'UP3', 'GRESIK', 'JL. DR. WAHIDIN SUDIRO HUSODO NO.134 GRESIK 61114', '(031) - 3974291', 
    'ï¿½3974294', '51', 'ANDI SENO HENDRIATMOKO', 'GRESIK', '05', 
    '5115', 'GSK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51JBR', 'UP3', 'JEMBER', 'JL. GAJAH MADA NO.198 JEMBER', '(0331) - 484641-2', 
    'ï¿½485766', '51', 'ALIMUDDIN', 'JEMBER', '06', 
    '5116', 'JBR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51KDR', 'UP3', 'KEDIRI', 'JL. JEND. BASUKI RACHMAD NO.1 KEDIRI', '(0354) - 682420', 
    'ï¿½682431', '51', 'DENY SETIAWAN', 'KEDIRI', '07', 
    '5117', 'KDR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51PSR', 'UP3', 'PASURUAN', 'JL. PANGLIMA SUDIRMAN NO. 69, PASURUAN', '(0343) - 426516-7', 
    ' 426518', '51', 'AGUS SUSANTO', 'PASURUAN', '08', 
    '5118', 'PSR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51MDN', 'UP3', 'MADIUN', 'JL. LET. JEND. HARYONO NO.30, MADIUN', '(0351) - 452267-9', 
    'ï¿½464366', '51', 'SUHANDOPO', 'MADIUN', '09', 
    '5119', 'MDN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51MLG', 'UP3', 'MALANG', 'JL. JEND. BASUKI RAHMAT NO. 100 MALANG', '(0341) - 326034-5', 
    'ï¿½362046', '51', 'AGUNG WIBOWO', 'MALANG', '10', 
    '5120', 'MLG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51SDA', 'UP3', 'SIDOARJO', 'JL. A. YANI NO.47-49, SIDOARJO', '(031) - 8955410-4', 
    'ï¿½8955415', '51', 'FERI ASMORO HERMANTO', 'SIDOARJO', '11', 
    '5121', 'SDA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51BJN', 'UP3', 'BOJONEGORO', 'JL. TEUKU UMAR NO.3, BOJONEGORO', '(0353) - 881271', 
    ' 881532', '51', 'YUSUF HADIYANTO', 'BOJONEGORO', '12', 
    '5122', 'BJN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51BWG', 'UP3', 'BANYUWANGI', 'JL. NUSANTARA NO.1 BANYUWANGI', '(0333) - 421441-2', 
    '421446', '51', 'DANANG SETIAWAN', 'BANYUWANGI', '13', 
    '5123', 'BWG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51STB', 'UP3', 'SITUBONDO', 'JL. CEMPAKA NO.35, SITUBONDO', '(0338) - 672905', 
    'ï¿½672908', '51', 'EKA PANJI SAPTAPRASETYA', 'SITUBONDO', '14', 
    '5124', 'STB');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51PMK', 'UP3', 'MADURA', 'JL. JOKOTOLE 127-A, PAMEKASAN', '(0324) - 332994,322115', 
    '322117', '51', 'FAHMI FAHRESI', 'PAMEKASAN', '15', 
    '5125', 'PMK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('51PON', 'UP3', 'PONOROGO', 'JL. DR. SOETOMO NO. 34 PONOROGO', '(0352) - 481147-481', 
    'ï¿½481147', '51', 'SUZANA ZEIN', 'PONOROGO', '16', 
    '5126', 'PON');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53BDG', 'UP3', 'BANDUNG', 'JL Soekarno Hatta No 436 Bandung 40255', '022-5222043', 
    '53', 'LEANDRA AGUNG TRI RADI PUTRA', 'Bandung');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53BGR', 'UP3', 'BOGOR', 'JL Pajajaran No 233 BOGOR TIMUR 16153', '0251-8345200', 
    '53', 'GRAHAITA GUMELAR', 'Bogor');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53BKS', 'UP3', 'BEKASI', 'JL Cut Meutia no 42 BEKASI 17113', '021-881222', 
    '53', 'DONNA SINATRA', 'Bekasi');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53BTS', 'UP3', 'BANTEN SELATAN', 'JL Hadiwinangun No 39 RANGKASBITUNG', '0252-281629', 
    '53', 'EDY MUKTASIM BILLAH', 'Banten Selatan');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53BTU', 'UP3', 'BANTEN UTARA', 'JL Pangeran Dipenogoro No 2 SERANG 42112', '0254-200716', 
    '53', 'ARIEF KUNCORO', 'Banten Utara');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53CJR', 'UP3', 'CIANJUR', 'JL Siti Jenab No 20 CIANJUR 43211', '0263-266222', 
    '53', 'ANDRE PRATAMA DJATMIKO', 'Cianjur');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53CMI', 'UP3', 'CIMAHI', 'Kolonel Masturi no 5/7 Cimahi 31023', '022-6647680', 
    '53', 'ARYTA WULANDARI', 'Cimahi');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53CRB', 'UP3', 'CIREBON', 'JL Tuparev no 100 Cirebon', '0231-236560', 
    '53', 'IMAM AHMADI', 'Cirebon');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53DPK', 'UP3', 'DEPOK', 'JL Sentosa Raya No 4 DEPOK TENGAH 16411', '021-7706269', 
    '53', 'GEBYAR PANDITO', 'Depok');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53GPI', 'UP3', 'GUNUNG PUTRI', 'Jl Camat Enjam No 13 Cileungsi', '0251-8230391', 
    '53', 'DARWIN SIMANJUNTAK', 'Gunung Putri');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53GRT', 'UP3', 'GARUT', 'JL Pramuka No 2 GARUT 41112', '0265-241147', 
    '53', 'ATIKAH DEWI ANGGRENY', 'Garut');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53KRW', 'UP3', 'KARAWANG', 'JL Raya Kertabumi No 36 KARAWANG 41311', '0267-402120', 
    '53', 'MAHADHIR', 'Karawang');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53MJA', 'UP3', 'MAJALAYA', 'JL Jaksa NAranata No 1 Bale Endah Majalaya', '022-5940281', 
    '53', 'WIDODO', 'Majalaya');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53PWK', 'UP3', 'PURWAKARTA', 'Jl Kornel Singawinata No 59 PURWAKARTA 43111', '0264-200033', 
    '53', 'KURNIAWAN FITRIANTO', 'Purwakarta');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53SKI', 'UP3', 'SUKABUMI', 'JL RE Martadinata No 39 SUKABUMI 43113', '0266-221160', 
    '53', 'YUNIAR BUDI SATRIO', 'Sukabumi');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53SMD', 'UP3', 'SUMEDANG', 'JL Palasari no 75 Sumedang 45322', '0261-201846', 
    '53', 'RAMDANI AGUSTIYANSAH, S.T.', 'Sumedang');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('53TSK', 'UP3', 'TASIKMALAYA', 'JL Mayor Utara No 28 Tasikmalaya 46132', '0265-331686', 
    '53', 'YUDHO RAHADIANTO', 'Tasikmalaya');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52000', 'UP3', 'KUDUS', 'JL. AKBP AGIL KUSUMAMADYA 102', '(0291) 433792', 
    '(0291) 438435', '52', 'FIRMAN SADIKIN', 'KUDUS', '01', 
    '5211', 'KDS');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52050', 'UP3', 'SURAKARTA', 'JL. BRIG. JEND SLAMET RIYADI 468', '(0271) 722091', 
    '(0271) 722095', '52', 'MOH SADLI', 'SURAKARTA', '02', 
    '5212', 'SKA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52100', 'UP3', 'YOGYAKARTA', 'JL. GEDONG KUNING NO 3 BANGUNTAPAN', '(0274) 452200', 
    '(0274) 452452', '52', 'SIGIT HARI WIBOWO', 'YOGYAKARTA', '03', 
    '5213', 'YGK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52150', 'UP3', 'MAGELANG', 'JL. JEND A. YANI NO 14', '(0293) 363355', 
    '(0293) 362144', '52', 'IMBAR SUSANTO', 'MAGELANG', '04', 
    '5214', 'MGL');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52200', 'UP3', 'PURWOKERTO', 'JL. JEND. SUDIRMAN NO 141', '(0281) 634220', 
    '(0281) 636456', '52', 'FIRMAN RAHARJA', 'PURWOKERTO', '05', 
    '5215', 'PWT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52250', 'UP3', 'TEGAL', 'JL. PEMUDA NO 9', '(0283) 358633', 
    '(0283) 351608', '52', 'MARYUDIN SALEH', 'TEGAL', '06', 
    '5216', 'TGL');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52300', 'UP3', 'SEMARANG', 'JL. PEMUDA 93', '(024) 3547651', 
    '(024) 3513708', '52', 'RICKI YAKOP', 'SEMARANG', '07', 
    '5217', 'SMG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52350', 'UP3', 'SALATIGA', 'JL. DIPONEGORO NO 19', '(0298) 326883', 
    '(0298) 327575', '52', 'VICKY REANDRY FARADIAN', 'SALATIGA', '08', 
    '5218', 'SLG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52400', 'UP3', 'KLATEN', 'JL. PERINTIS KEMERDEKAAN NO 3A', '(0272) 320912', 
    '(0272) 326073', '52', 'AGUS YUDHISTIRA SUJANA', 'KLATEN', '09', 
    '5219', 'KLT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52450', 'UP3', 'PEKALONGAN', 'JL. MANGGIS NO 2', '(0285) 434784', 
    '(0285) 421001', '52', 'NURHIDAYANTO NUGROHO', 'PEKALONGAN', '10', 
    '5220', 'PKL');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('52500', 'UP3', 'CILACAP', 'JL. BRIG. JEND. KATAMSO NO 52', '(0282) 521041', 
    '(0282) 533075', '52', 'ADITYA SETIAWAN', 'CILACAP', '11', 
    '5221', 'CLP');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('52090', 'UP3', 'KANTOR DISTRIBUSI', ' ', '52', 
    'FERRY KRISNA', 'SEMARANG', '12', '5222', 'SMG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('55SLT', 'UP3', 'BALI SELATAN', 'ALAMAT', 'TELEPON', 
    'FAX', '55', 'I PUTU KARIANA', 'BALI', '551', 
    'BALI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('55TMR', 'UP3', 'BALI TIMUR', 'ALAMAT', 'TELEPON', 
    'FAX', '55', 'IMADYA NARESWARI', 'BALI', '552', 
    'BALI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('55UTR', 'UP3', 'BALI UTARA', 'ALAMAT', 'TELEPON', 
    'FAX', '55', 'ELASHINTA', 'BALI', '553', 
    'BALI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPERP, 
    NMSINGKAT)
 Values
   ('55JTM', 'UP3', 'PRIMA', 'ALAMAT', 'TELEPON', 
    'FAX', '55', 'DANIEL LESTANTO', 'BALI', '554', 
    'BALI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('16BGK', 'UP3', 'BANGKA', 'JL JEND SUDIRMAN NO 180', '0717-431661', 
    '16', 'MUHAMMAD TAUFIK', 'PANGKALPINANG', 'BGK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22BJM', 'UP3', 'BANJARMASIN', 'JL. LAMBUNG MANGKURAT NO 12', '(0511) 3354992, 3351158', 
    '(0511) 3353610', '22', 'YANUAR', 'BANJARMASIN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22PRY', 'UP3', 'PALANGKA RAYA', 'JL. A. YANI NO 1', '(0536) 3221444', 
    '(0536) 3222444', '22', 'PURWANTO', 'PALANGKARAYA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22BRB', 'UP3', 'BARABAI', 'JL. ABDUL MUIS REDHANI NO. 62', '(0517) 42258', 
    '(0517) 41503', '22', 'MUHAMAD MUSA', 'BARABAI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22KKP', 'UP3', 'KUALA KAPUAS', 'JL. PATIH RUMBIH NO. 70', '(0513) 21368', 
    '(0513) 23858', '22', 'FX EKA WIJAYANTO', 'KUALA KAPUAS');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22KTB', 'UP3', 'TANAH BUMBU', 'JL. H. HASAN BASRI NO. 4', '(0518) 21248, 21526', 
    '(0518) 21229', '22', 'ANAS FEBRIAN', 'KOTABARU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('41ABN', 'UP3', 'AMBON', 'JL. KAPT. PIERE TENDEAN HALONG AMBON', '41', 
    'RAMLI MALAWAT', 'AMBON', 'AMBON');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('41TAL', 'UP3', 'TUAL', 'JL. SOEKARNO-HATTA No.40', '0916 21749', 
    '41', 'SASONGKO ARIBOWO', 'TUAL', 'TUAL');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('41TNT', 'UP3', 'TERNATE', 'Jl. A. YANI N0. 40, TERNATE, MAlUKU UTARA', '41', 
    'MUFID ARIANTO', ' TERNATE', ' TERNATE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11BNA', 'UP3', 'BANDA ACEH', 'XXX', '123', 
    '123', '11', 'EKA RAHMADANIATI', 'BANDA ACEH');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11LSA', 'UP3', 'LANGSA', 'XX', '123', 
    '123', '11', 'INDRADI PRATAMA', 'LANGSA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11LSM', 'UP3', 'LHOKSEUMAWE', 'XXX', '12345', 
    '12345', '11', 'HUSNI', 'LHOKSEUMAWE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11MBO', 'UP3', 'MEULABOH', 'XXX', '123', 
    '123', '11', 'ACHMAD ARIANSYAH', 'MEULABOH');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11SBS', 'UP3', 'SUBULUS SALAM   ', 'XXX', '123', 
    '123', '11', 'ANDHI PRASETIAWAN', 'SUBULUSSALAM');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('11SGL', 'UP3', 'SIGLI             ', 'XX', '123', 
    '123', '11', 'M.AKBAR HURIANDA, ST', 'SIGLI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12120', 'UP3', 'MEDAN', 'JL. LISTRIK NO.8', '12', 
    'EDY SAPUTRA', 'MEDAN', 'MED');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12126', 'UP3', 'LUBUK PAKAM', 'JL. DIPONEGORO', '12', 
    'M. HARRYADI POEL', 'LUBUK PAKAM', 'PKM');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12122', 'UP3', 'BINJAI', 'JL.TEUKU AMIR HAMZAH NO.37', '12', 
    'MUHAMMAD ISRA', 'BINJAI', 'BJI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12121', 'UP3', 'PEMATANGSIANTAR', 'JL. KAPT. MH SITORUS NO.1 P. SIANTAR', '12', 
    'RAMSES MANALU', 'PEMATANGSIANTAR', 'PMS');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12125', 'UP3', 'RANTAU PRAPAT', 'JL. LISTRIK NO 1 RANTAU PRAPAT', '12', 
    'DWITA ASWIYANTI SYAFITRI', 'RANTAU PRAPAT', 'RAP');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12123', 'UP3', 'SIBOLGA', 'JL. DR F.L. TOBING NO 27 SIBOLGA', '12', 
    'SENDY RUDIANTO', 'SIBOLGA', 'SBG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12124', 'UP3', 'PADANG SIDIMPUAN', 'JL. SM. RAJA NO II BATUNA DUA SIDEMPUAN', '12', 
    'YESSI INDRA', 'PADANGSIDIMPUAN', 'PSP');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12127', 'UP3', 'NIAS', 'JL. GOMO', '12', 
    'LEONARD TULUS PANJAITAN', 'NIAS', 'NIA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31100', 'UP3', 'MANADO', 'JL. JEND. A. YANI NO. 32 ', '(0431) 862144', 
    '(0431) 864144', '31', 'REVI ALDRIAN', 'MANADO', 'MDO');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31200', 'UP3', 'PALU', 'JL. RA. KARTINI NO. 26', '(0451) 455222', 
    '(0451) 421088', '31', 'ANSAR', 'PALU', 'PLU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31500', 'UP3', 'TOLITOLI', 'JL. SUDIRMAN, NO. 66', '(0453) 23750', 
    '(0453) 21668', '31', 'ICUK SULISTIANTO', 'TOLITOLI', 'TLI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31600', 'UP3', 'GORONTALO', 'JL. JEND. SUDIRMAN NO. 63', '(0435) 821936', 
    '(0435) 824474', '31', 'HARDI', 'GORONTALO', 'GTO');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31700', 'UP3', 'KOTAMOBAGU', 'JL. PALOKO, NO. 2 ', '(0434) 21244', 
    '(0434) 21583', '31', 'HENGKY PURBO LESMONO', 'KOTAMOBAGU', 'KTM');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31800', 'UP3', 'TAHUNA', 'JL. BARU TONA NO. 28 ', '(0432) 21410', 
    '(0432) 21762', '31', 'RADEN MAS DIMAS ADHI PRABOWO', 'TAHUNA', 'THN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('31900', 'UP3', 'LUWUK', 'JL URIP SUMOHARJO NO. 1', '(0461) 21830', 
    '(0461) 325185', '31', 'RIDWAN BOGIE RISMAWAN', 'LUWUK', 'LWK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('13100', 'UP3', 'PADANG', 'JL. DR.WAHIDIN NO.8', '0751-7535005', 
    '0751-7535002', '13', 'DIAN WIDIANA KUSWARA', 'PADANG', '13', 
    '13', 'CPDG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('13200', 'UP3', 'BUKITTINGGI', 'JL. JEND.SUDIRMAN NO. 1', '0752-33589', 
    '0752-22587', '13', 'RUDI HAMIRI', 'BUKITTINGGI', '13', 
    '13', 'CBKT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('13300', 'UP3', 'SOLOK', 'JL. PROF.DR.HAMKA NO. 81', '0755-20466', 
    '0755-20383', '13', 'HARIANI', 'SOLOK', '13', 
    '13', 'CSLK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, UNITAPLAMA, 
    UNITAPERP, NMSINGKAT)
 Values
   ('13400', 'UP3', 'PAYAKUMBUH', 'JL. PROF.DR.M. YAMIN NO. 52', '0752-92005', 
    '0752-92932', '13', 'TEGUH BUDI OCTAVIANTO', 'PAYAKUMBUH', '13', 
    '13', 'CPYK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('18DMI', 'UP3', 'DUMAI', 'JALAN JEND SUDIRMAN NO. 173', '18', 
    'MANIHAR HUTAJULU', 'DMI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('18PKU', 'UP3', 'PEKANBARU', 'JALAN DR.SUTOMO', '18', 
    'WILSRIZA WILMAR', 'PKU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('18RGT', 'UP3', 'RENGAT', 'JALAN LINTAS TIMUR PEMATANG REBA', '18', 
    'TATOK WINARKO   ', 'RGT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('18TPI', 'UP3', 'TANJUNGPINANG', 'JALAN BAKAR BATU NO.55', '18', 
    'RULLY AGUS WIDANARTO', 'TPI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('42BIK', 'UP3', 'BIAK', 'WILAYAH PAPUA', '42', 
    'HERY SUPRIYADI', 'PAPUA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('42JYP', 'UP3', 'JAYAPURA', 'JL. A. YANI', '42', 
    'MARTHEN HENDERSON', 'KOTAMADYA JAYAPURA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('42MNK', 'UP3', 'MANOKWARI', 'JL. BANDUNG MANOKWARI', '42', 
    'FREDRIK MAURIDS NORIWARI', 'PAPUA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('42MRK', 'UP3', 'MERAUKE', 'WILAYAH PAPUA', '42', 
    'ADE ARRANG MALLE MANTIRI', 'PAPUA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('42SOR', 'UP3', 'SORONG', 'JL. JEND. A. YANI NO.7 KLALIGI SORONG', '42', 
    'DONI HERNANDI', 'PAPUA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('21PTK', 'UP3', 'PONTIANAK', 'JL. JEND A YANI NO.25', '0561734420', 
    '0561749041', '21', 'BLASIUS GANI', 'PONTIANAK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('21SKW', 'UP3', 'SINGKAWANG', 'JL. ALIANYANG NO. 71', '0562631725', 
    '0562632016', '21', 'MARTINUS I. PASENSI', 'SINGKAWANG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('21SGU', 'UP3', 'SANGGAU', 'JL. DR. SETIA BUDI NO.1', '056421015', 
    '056422016', '21', 'HENDY GITA WEDHATAMA', 'SANGGAU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('21KTP', 'UP3', 'KETAPANG', 'JL. LETKOL M. TOHIRNO. 147', '053432381', 
    '053433277', '21', 'YUSRIZAL IBRANI', 'KETAPANG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('44MTR', 'UP3', 'MATARAM', 'JL YOS SUDARSO NO 2', '(0370) 622793', 
    '(0370) 632029', '44', 'ADRIAN SITOMPUL', 'MATARAM', 'MTR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('44SBW', 'UP3', 'SUMBAWA', 'JL SETIABUDI NO 18', '(0371) 21028', 
    '(0371) 21427', '44', 'FIRMAN SULISTYAWAN', 'SUMBAWA', 'SBW');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('44BIM', 'UP3', 'BIMA', 'JL SOEKARNO HATTA', '(0374) 43685-43686', 
    '(0374) 43265', '44', 'SYAIFUL HANNAN', 'BIMA', 'BIM');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CWP', 'UP3', 'WATAMPONE', 'JL JEND SUDIRMAN NO. 32', '(0481) 21757, 22220', 
    '(0481) 23094', '32', 'RIDJAL ABDUL RASYID', 'WATAMPONE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CKD', 'UP3', 'KENDARI', 'JL JEND A. YANI NO.1', '(0401) 390444, 390985', 
    '(0401) 390084', '32', 'MUNAWIR LILING', 'KENDARI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CPG', 'UP3', 'PINRANG', 'JL JEND SOEKAWATI NO, 24', '(0421) 921220, 923333', 
    '(0421) 921005', '32', 'DADANG WAHYUDI', 'PINRANG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CPR', 'UP3', 'PARE PARE', 'JL VETERAN NO. 32', '(0421) 25444, 22932', 
    '(0421) 216977', '32', 'AGUNG PRATOMO', 'PARE PARE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CPL', 'UP3', 'PALOPO', 'JL MERDEKA NO. 70', '(0471) 24001, 24008', 
    '(0471) 24005', '32', 'YEKTI KURNIAWAN', 'PALOPO');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CBK', 'UP3', 'BULUKUMBA', 'JL LANTO DG PASEWANG', '(0413) 82000, 83000', 
    '(0413) 81591', '32', 'AGUS PRIYANTO', 'BULUKUMBA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CBB', 'UP3', 'BAU BAU', 'JL JEND. SUDIRMAN NO. 62', '(0402) 2822200, 2824435', 
    '(0402) 2822100', '32', 'BAGUS CAHYADI', 'BAU BAU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32CMJ', 'UP3', 'MAMUJU', 'JL RANGGONG NO. 26', '(0426) 2700099, 2700100', 
    '(0426) 2106', '32', 'M. FAUZAN', 'MAUMUJU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('17171', 'UP3', 'TANJUNG KARANG', 'JL. P. DIPONEGORO NO. 14 ', '0721 - 263206', 
    '0721 - 264200', '17', 'PRESLY SILAEN', 'BANDAR LAMPUNG', 'TGK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('17172', 'UP3', 'METRO', 'Jl. AR. PRAWIRANEGARA NO. 99 15 A KAUMAN  34111', '0725 - 45699', 
    '0725 - 7850929', '17', 'M. BURHANUDDIN HASAN', 'METRO', 'MTR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('17173', 'UP3', 'KOTABUMI', 'JL. SOEKARNO HATTA NO. 149', '0724 - 21166 / 24858', 
    '0724 - 22555', '17', 'ABRAR', 'KOTABUMI', 'KTB');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14JMB', 'UP3', 'JAMBI', 'JL.URIP SUMOHARJO NO.2', '0741-63100', 
    '741669629', '14', 'EDIWAN', 'JAMBI', 'JMB');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14PLB', 'UP3', 'PALEMBANG', 'JL.KAPTEN A.RIVAI NO.37', '0711-357560', 
    '357575', '14', 'HENRY NUGROHO', 'PALEMBANG', 'PLB');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14LHT', 'UP3', 'LAHAT', 'JL KOL M NUH LEMBAYUNG LAHAT', '0731-322828', 
    '0731-321753', '14', 'TEGUH AANG HARMADI', 'LAHAT', 'LHT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14MBO', 'UP3', 'MUARA BUNGO', 'JL.SULTAN THAHA', '0747-27179', 
    '323420', '14', 'AGUS FITRYANSYAH', 'MUARA BUNGO', 'MBO');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14BKL', 'UP3', 'BENGKULU', 'JL. PROF DR HAZAIRIN NO 8', '073621969', 
    '073620926', '14', 'ANJAR_WIDYATAMA', 'BENGKULU', 'BKL');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('23BRU', 'UP3', 'BERAU', 'Jl. SA Maulana No 1 Tanjung Redeb', '055421062', 
    '23', 'RIZKI RHAMDAN YUSUP', 'BERAU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('23BTG', 'UP3', 'BONTANG', 'Jl. M. T. Haryono - BONTANG', '054821448', 
    '23', 'SRI WAHYUNINGSIH', 'BONTANG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('23SMD', 'UP3', 'SAMARINDA', 'Jl. Gajah Mada No. 23 SAMARINDA', '0541741531', 
    '23', 'HENDRA IRAWAN', 'SAMARINDA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('23BPN', 'UP3', 'BALIKPAPAN', 'Jl. Jendral Sudirman No. 117 BPP', '0542733559', 
    '23', 'ARIEF PRASTYANTO', 'BALIKPAPAN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('43KPG', 'UP3', 'KUPANG', 'JL PALAPA NO 27', '43', 
    'NIKOLAS DENIS ADRIAN', 'KUPANG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('43SMB', 'UP3', 'SUMBA', 'JL. AHMAD YANI 25 SUMBA', '123', 
    '123', '43', 'RONALD TILMANS', 'SUMBA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('43FBB', 'UP3', 'FLORES BAGIAN BARAT', 'JL. ELTARI II ENDE', '43', 
    'EKI PUTRA', 'ENDE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('43FBT', 'UP3', 'FLORES BAGIAN TIMUR', 'JL. GAJAH MADA NO 12', '43', 
    'EKO RIDUWAN', 'MAUMERE');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, NMSINGKAT)
 Values
   ('56100', 'UP3', 'BANTEN UTARA', 'JL Pangeran Dipenogoro No 2 SERANG 42112', '0254-200716', 
    '56', 'HANFI ANDRHEAN ABIDIN', '56');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, NMSINGKAT)
 Values
   ('56200', 'UP3', 'BANTEN SELATAN', 'JL Hadiwinangun No 39 RANGKASBITUNG', '0252-281629', 
    '56', 'MUHAMMAD ARDIAN', '56');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('56610', 'UP3', 'CIKOKOL', 'Jl. Jend Sudirman No. 1 ', '56', 
    'BADRUZ ZAMAN', '56', '566', '610');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('56620', 'UP3', 'SERPONG', 'Jl. Raya Serpong BSD Sektor 8', '56', 
    'YUDI LORDIANTO,ST', 'TANGERANG', '56', '566', '620');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('56640', 'UP3', 'CIKUPA', 'Jl. Raya Serang Km 17, Cikupa', '56', 
    'DIDIK KRISMANTO', '56', '566', '640');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('56660', 'UP3', 'TELUK NAGA', 'Jl. Raya Kampung Melayu No.11', '56', 
    'MUHAMMAD WARDI HADI', '56', '566', '660');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, UNITAPLAMA, UNITAPERP, NMSINGKAT)
 Values
   ('56820', 'UP3', 'PRIMA TANGERANG', 'Pekan Raya Jakarta', '56', 
    'JATI G.P. SIAHAAN AK', '56', '568', '820');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('41MSH', 'UP3', 'MASOHI', ' Jl. Abdullah Souisa Masohi ', '41', 
    'YB WAWAN DWI P', 'MASOHI', 'MASOHI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('41SFF', 'UP3', 'SOFIFI', 'Jl. Pemuda Sofifi   ', '41', 
    'ILHAM SUNDA DIPUTRA', ' SOFIFI', 'SOFIFI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('42TMK', 'UP3', 'TIMIKA', 'JL. HASANUDDIN', '0901-321142', 
    '0901-321142', '42', 'PARMONANGAN ANDREAS SITORUS', 'KOTA TIMIKA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32AMS', 'UP3', 'MAKASSAR SELATAN', 'JL MONGINSIDI NO. 2 ', '(0411) 870011, 870088', 
    '(0411) 876688', '32', 'JIMY INDRA BASKARA', 'MAKASSAR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('32AMU', 'UP3', 'MAKASSAR UTARA', 'JL JEND AHMAD YANI NO. 27-29', '(0411) 319905, 312842', 
    '32', 'ALEXANDER J. MANUHUWA', 'MAKASSAR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('32MKS', 'UP3', 'MAKASSAR', 'JL MONGINSIDI NO. 2 ', '(0411) 870011, 870088', 
    '(0411) 876688', '32', 'KHAIRULLAH,ST', 'MAKASSAR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('16TJP', 'UP3', 'BELITUNG', 'JL SUDIRMAN', '16', 
    'MEGANTARA VILANDA KURNIAWAN', 'TANJUNG PANDAN', 'BLT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('52550', 'UP3', 'GROBOGAN', 'JL. RAYA DEMAK PURWODADI KM 3 WONOSALAM DEMAK', '(0291) 6910334', 
    '52', 'ARTIKA HADI WIBAWA', 'DEMAK', 'DMK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('23TRK', 'UP3', 'TARAKAN', 'JLN. P. DIPONEGORO NO 1 GUNUNG BELAH SEBENGKOK', '23', 
    'MANAGER ULP TARAKAN', 'TARAKAN', 'TRK');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('52650', 'UP3', 'SUKOHARJO', 'RUKO SOLO PERMAI HC-6, JL. IR. SOEKARNO, GROGOL', '52', 
    'INDRI MEGANANDA', 'SUKOHARJO', 'SKH');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('53CKG', 'UP3', 'CIKARANG', 'JL KIHAJAR DEWANTARA BLOK C NO 2 CIKARANG BEKASI', '53', 
    'WIEDHYARNO ARIEF WICAKSONO', 'KABUPATEN BEKASI', 'CKG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('53IDM', 'UP3', 'INDRAMAYU', 'JL S PARMAN NO 1 - KAB. INDRAMAYU KODE POS. 45211', '53', 
    'SUHARNO', 'KABUPATEN INDRAMAYU', 'IDM');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12128', 'UP3', 'MEDAN UTARA', 'JLN. K.L.YOS SUDARSO NO.115 MEDAN', '12', 
    'HIRO PINGKIR PARDEDE', 'MEDAN', 'MDU');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('12129', 'UP3', 'BUKIT BARISAN', 'JLN. GUNDALING BRASTAGI', '12', 
    'RAMSES HUTAJULU', 'KABANJAHE', 'BBN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA, NMSINGKAT)
 Values
   ('14OGI', 'UP3', 'OGAN ILIR', 'JALAN PALEMBANG-INDRALAYA KM 36', '14', 
    'ARIF AZANNY', 'INDERALAYA', 'OGI');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('41TBO', 'UP3', 'TOBELO', 'Jl. Raya Wosia, Desa Wosia kec. Tobelo tengah', '0', 
    '41', 'ANTON TONAPA', 'KAB. HALMAHERA UTARA', 'TOBELO');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('41SLK', 'UP3', 'SAUMLAKI', 'Jl. Poros Sifnana, Kec. Tanimbar Selatan', '0', 
    '41', 'HENDRIK FERDINAND S', 'KAB. MALUKU TENGGARA BARAT');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('42WMN', 'UP3', 'WAMENA', 'Jl. Ahmad Yani No. 33 Wamena', '(0969) 31097', 
    '42', 'MAHLY JEREMOT KBAREK', 'Wamena', 'WMN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('42NBR', 'UP3', 'NABIRE', 'Jl. Pemuda No. 36 Nabire, Papua', '(0984) 21082', 
    '42', 'RAKHEL MONIKA RUMBEWAS', 'Nabire', 'NBR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('23KTR', 'UP3', 'KALIMANTAN UTARA', 'Jl. Sengkawit, Tanjung Selor, Bulungan', '0552-21200', 
    '0', '23', 'DODY SUHENDRA', 'TANJUNG SELOR', 'KTR');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    UNITUPI, MANAGER, KOTA)
 Values
   ('23IKN', 'UP3', 'NUSANTARA', 'Jl. A Rahman Hakim RT.15 Desa.Sukaraja Kec.Sepaku', '0', 
    '23', 'RAKHMAD K. PANIGORO', 'PENAJAM PASER UTARA');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('17174', 'UP3', 'PRINGSEWU', 'Jl. Satria No.706, Pringsewu Barat, Lampung 35373', '(0729)21187', 
    '(0729)22589', '17', 'EKA NURWATI', 'PRINGSEWU', 'PSW');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, UNITUPI, 
    MANAGER, KOTA)
 Values
   ('18BKN', 'UP3', 'BANGKINANG', 'Jl. Ahmad Yani No.42 Bangkinang Kota', '18', 
    'TRI HARYANTO', 'BKN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('21MPW', 'UP3', 'MEMPAWAH', 'JL.Gusti M. Taufik, Kel.Terusan Kec.Mempawah Hilir', '(0561)561123', 
    '(0561)561123', '21', 'ABDUL AZIS P', 'KAB. MEMPAWAH', 'MPW');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('14LLG', 'UP3', 'LUBUK LINGGAU', 'Jl. Yos Sudarso, Kel Simpang Periuk', '0', 
    '0', '14', 'MOCH. JULNANSYAH NUGROHO', 'LUBUK LINGGAU', 'LLG');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA)
 Values
   ('22PBN', 'UP3', 'PANGKALAN BUN', 'Jl. Utama Pasir Panjang, Ruko VKL Blok B4-5-6', '0', 
    '0', '22', 'SAUT PARDOMUAN PANDJAITAN', 'PANGKALAN BUN');
Insert into UNITAP
   (UNITAP, SATUAN, NAMA, ALAMAT, TELEPON, 
    FAXIMILE, UNITUPI, MANAGER, KOTA, NMSINGKAT)
 Values
   ('44SLP', 'UP3', 'SELAPARANG', 'Jl. TGH. Zainudin Abdul Majid, Kecamatan Selong', '0', 
    '0', '44', 'SENO WURYANTO', 'SELAPARANG', 'SLP');
COMMIT;
