CREATE TABLE UNITUP
(
  UNITUP       VARCHAR2(5 BYTE),
  SATUAN       VARCHAR2(25 BYTE),
  NAMA         VARCHAR2(25 BYTE),
  ALAMAT       VARCHAR2(50 BYTE),
  TELEPON      VARCHAR2(25 BYTE),
  FAXIMILE     VARCHAR2(25 BYTE),
  UNITAP       VARCHAR2(10 BYTE),
  MANAGER      VARCHAR2(50 BYTE),
  KOTA         VARCHAR2(50 BYTE),
  NMSINGKAT    VARCHAR2(10 BYTE),
  KDNOPEL      VARCHAR2(2 BYTE),
  UNITUPKARGO  VARCHAR2(5 BYTE),
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)