DECLARE
    v_id_g1 NUMBER;
    v_id_t1 NUMBER;
    v_id_t11 NUMBER;
    v_id_b1 NUMBER;
    v_id_t12 NUMBER;
    v_id_b2 NUMBER;
    v_id_k0 NUMBER;
    v_id_k1 NUMBER;
    v_id_t121 NUMBER;
    v_id_b4 NUMBER;
    v_id_k3 NUMBER;
    v_id_k5 NUMBER;
BEGIN
    -- === Lokasi Desa Bangunharja - Cisaga (Ciamis) ===
    -- Gardu G1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP,
        KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, SPESIFIKASI,
        LATITUDE, LONGITUDE, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID, NAMA_PROJEK
    ) VALUES (
        '53','53TSK','53221',
        '32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'G1','GARDU','TRAFO 307 KV',
        -7.3400,108.5300,'LAMA',0,'admin','BPBL 2025'
    ) RETURNING ID_JARINGAN INTO v_id_g1;

    -- Tiang 1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP,
        KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE,
        PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'T1','TIANG', -7.3410,108.5310,v_id_g1,'LAMA',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_t1;

    -- Kabel G1 -> T1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI,
        KD_KAB, KABUPATENKOTA, KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, SPESIFIKASI,
        PARENT_ID, TARGET_ID, VOLUME, KDSATUAN, SATUAN, TRANSMISI,
        STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT',
        '3207','CIAMIS','320711','CISAGA','3207112002','BANGUNHARJA',
        'K0','KABEL','NYFGbY 3x70 mm²',
        v_id_g1,v_id_t1,50,'M','Meter','TR','LAMA',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_k0;

    -- Tiang 1.1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE,
        PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'T1.1','TIANG', -7.3420,108.5320,v_id_t1,'LAMA',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_t11;

    -- Rumah B1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE,
        PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'B1','PELANGGAN', -7.3430,108.5330,v_id_t11,'BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_b1;

    -- Tiang 1.2
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE,
        PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'T1.2','TIANG', -7.3440,108.5340,v_id_t1,'BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_t12;

    -- Rumah B2
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE,
        PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'B2','PELANGGAN', -7.3448,108.5350,v_id_t12,'BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_b2;

    -- Kabel T1 -> T1.2
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, SPESIFIKASI, PARENT_ID, TARGET_ID,
        VOLUME, KDSATUAN, SATUAN, TRANSMISI,
        STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'K1','KABEL','AAAC 3x70 mm²',v_id_t1,v_id_t12,30,'M','Meter','TR','BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_k1;

    -- Tiang cabang T1.2.1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, PARENT_ID, STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'T1.2.1','TIANG', -7.3455,108.5360,v_id_t12,'BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_t121;

    -- Rumah B4 dari T1.2.1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, PARENT_ID,
        STATUS_LAPANGAN, RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT','3207','CIAMIS',
        '320711','CISAGA','3207112002','BANGUNHARJA',
        'B4','PELANGGAN', -7.3462,108.5370,v_id_t121,'BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_b4;

    -- Kabel T1.2 -> T1.2.1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI,
        KD_KAB, KABUPATENKOTA, KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, SPESIFIKASI, PARENT_ID, TARGET_ID,
        VOLUME, KDSATUAN, SATUAN, TRANSMISI, STATUS_LAPANGAN,
        RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT',
        '3207','CIAMIS','320711','CISAGA','3207112002','BANGUNHARJA',
        'K3','KABEL','NYFGbY 3x35 mm²',v_id_t12,v_id_t121,20,'M','Meter','TR','BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_k3;

    -- Kabel T1.2.1 -> B4
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK (
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI,
        KD_KAB, KABUPATENKOTA, KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, SPESIFIKASI, PARENT_ID, TARGET_ID,
        VOLUME, KDSATUAN, SATUAN, TRANSMISI, STATUS_LAPANGAN,
        RUPIAH_SATUAN, USERID
    ) VALUES (
        '53','53TSK','53221','32','JAWA BARAT',
        '3207','CIAMIS','320711','CISAGA','3207112002','BANGUNHARJA',
        'K5','KABEL','NYFGbY 3x25 mm²',v_id_t121,v_id_b4,15,'M','Meter','TR','BARU',0,'admin'
    ) RETURNING ID_JARINGAN INTO v_id_k5;

    COMMIT;
END;
/
