DECLARE
    v_id_t1 NUMBER;
    v_id_t2 NUMBER;
    v_id_t3 NUMBER;
    v_id_t4 NUMBER;
BEGIN
    -- Tiang 1
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK(
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, STATUS_LAPANGAN
    )
    VALUES(
        '53', '53BJR', '53001', '32', 'JAWA BARAT', '3211', 'BANJAR',
        '3211010', 'KOTA BANJAR', '3211010001', 'BANJAR WETAN',
        'T1_BJR', 'TIANG', -7.3480, 108.5340, 'BARU'
    )
    RETURNING id_jaringan INTO v_id_t1;

    -- Tiang 2
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK(
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, STATUS_LAPANGAN
    )
    VALUES(
        '53', '53BJR', '53001', '32', 'JAWA BARAT', '3211', 'BANJAR',
        '3211010', 'KOTA BANJAR', '3211010002', 'BANJAR KIDUL',
        'T2_BJR', 'TIANG', -7.3485, 108.5345, 'BARU'
    )
    RETURNING id_jaringan INTO v_id_t2;

    -- Tiang 3
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK(
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, STATUS_LAPANGAN
    )
    VALUES(
        '53', '53BJR', '53001', '32', 'JAWA BARAT', '3211', 'BANJAR',
        '3211010', 'KOTA BANJAR', '3211010003', 'BANJAR LOR',
        'T3_BJR', 'TIANG', -7.3490, 108.5350, 'BARU'
    )
    RETURNING id_jaringan INTO v_id_t3;

    -- Tiang 4
    INSERT INTO LISDESBPBL.TRANS_JARINGAN_LISTRIK(
        UNITUPI, UNITAP, UNITUP, KD_PROV, PROVINSI, KD_KAB, KABUPATENKOTA,
        KD_KEC, KECAMATAN, KD_KEL, DESAKELURAHAN,
        KODE_SYSTEM, KATEGORI, LATITUDE, LONGITUDE, STATUS_LAPANGAN
    )
    VALUES(
        '53', '53BJR', '53001', '32', 'JAWA BARAT', '3211', 'BANJAR',
        '3211010', 'KOTA BANJAR', '3211010004', 'BANJAR KIDUL UTARA',
        'T4_BJR', 'TIANG', -7.3495, 108.5355, 'BARU'
    )
    RETURNING id_jaringan INTO v_id_t4;

    COMMIT;
END;
/
